// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CMessageID.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace XsfPb {

  /// <summary>Holder for reflection information generated from CMessageID.proto</summary>
  public static partial class CMessageIDReflection {

    #region Descriptor
    /// <summary>File descriptor for CMessageID.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CMessageIDReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBDTWVzc2FnZUlELnByb3RvEgZ4c2ZfcGIqlQEKBkNNU0dJRBIICgROb25l",
            "EAASFAoQQ2x0X0d0X0hhbmRzaGFrZRABEhQKEEd0X0NsdF9IYW5kc2hha2UQ",
            "AhIUChBDbHRfR3RfSGVhcnRiZWF0EAMSFAoQR3RfQ2x0X0hlYXJ0YmVhdBAE",
            "Eg0KCEx1YVN0YXJ0EIACEhAKC0NsdF9MX0xvZ2luEIECEggKA01heBCACGIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::XsfPb.CMSGID), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 客户端消息ID
  /// </summary>
  public enum CMSGID {
    [pbr::OriginalName("None")] None = 0,
    /// <summary>
    /// client --> gate 握手请求
    /// </summary>
    [pbr::OriginalName("Clt_Gt_Handshake")] CltGtHandshake = 1,
    /// <summary>
    /// gate --> client 握手反馈
    /// </summary>
    [pbr::OriginalName("Gt_Clt_Handshake")] GtCltHandshake = 2,
    /// <summary>
    /// client --> gate 心跳 请求
    /// </summary>
    [pbr::OriginalName("Clt_Gt_Heartbeat")] CltGtHeartbeat = 3,
    /// <summary>
    /// gate --> client 心跳 反馈
    /// </summary>
    [pbr::OriginalName("Gt_Clt_Heartbeat")] GtCltHeartbeat = 4,
    /// <summary>
    /// Lua消息ID起始值
    /// </summary>
    [pbr::OriginalName("LuaStart")] LuaStart = 256,
    /// <summary>
    /// client --> login 登录
    /// </summary>
    [pbr::OriginalName("Clt_L_Login")] CltLLogin = 257,
    [pbr::OriginalName("Max")] Max = 1024,
  }

  #endregion

}

#endregion Designer generated code
