// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SMessageID.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace XsfPbid {

  /// <summary>Holder for reflection information generated from SMessageID.proto</summary>
  public static partial class SMessageIDReflection {

    #region Descriptor
    /// <summary>File descriptor for SMessageID.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SMessageIDReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBTTWVzc2FnZUlELnByb3RvEgh4c2ZfcGJpZCqNBQoGU01TR0lEEg8KC1NN",
            "U0dJRF9Ob25lEAASCgoFU3RhcnQQuBcSEwoOQ2NfQ19IYW5kc2hha2UQuRcS",
            "EwoOQ19DY19IYW5kc2hha2UQuhcSEwoOQ2NfQ19IZWFydGJlYXQQuxcSFAoP",
            "Q2NfQ19TZXJ2ZXJJbmZvEL0XEhQKD0NfQ2NfU2VydmVySW5mbxC+FxIUCg9D",
            "Y19DX1NlcnZlckxvc3QQvxcSFAoPQ19DY19TZXJ2ZXJMb3N0EMAXEhIKDUNj",
            "X0NfU2VydmVyT2sQwRcSEgoNQ19DY19TZXJ2ZXJPaxDCFxIOCglDX0NjX1N0",
            "b3AQwxcSFQoQR3RfR3RBX0hhbmRzaGFrZRCcGBIVChBHdEFfR3RfSGFuZHNo",
            "YWtlEJ0YEhUKEEd0X0d0QV9IZWFydGJlYXQQnhgSFwoSR3RfR3RBX0NsaWVu",
            "dENsb3NlEJ8YEhwKF0d0QV9HdF9DbGllbnREaXNjb25uZWN0EKAYEhkKFEd0",
            "QV9HdF9DbGllbnRNZXNzYWdlEKEYEhUKEEd0QV9HdF9Ccm9hZGNhc3QQohgS",
            "FwoSR3RBX0d0X1NldFNlcnZlcklkEKMYEhUKEERiY19EYl9IYW5kc2hha2UQ",
            "gBkSFQoQRGJfRGJjX0hhbmRzaGFrZRCBGRIVChBEYmNfRGJfSGVhcnRiZWF0",
            "EIIZEhMKDkRiY19EYl9SZXF1ZXN0EIMZEhQKD0RiX0RiY19SZXNwb25zZRCE",
            "GRITCg5IY19IX0hhbmRzaGFrZRDkGRITCg5IX0hjX0hhbmRzaGFrZRDlGRIT",
            "Cg5IY19IX0hlYXJ0YmVhdBDmGRIQCgtHX0dfSHViVGVzdBDIGhIPCgpTTVNH",
            "SURfTWF4EIgnYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::XsfPbid.SMSGID), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 客户端消息ID
  /// </summary>
  public enum SMSGID {
    [pbr::OriginalName("SMSGID_None")] None = 0,
    [pbr::OriginalName("Start")] Start = 3000,
    /// <summary>
    ///MESSAGE_ID_START
    /// MESSAGE_ID_START
    /// </summary>
    [pbr::OriginalName("Cc_C_Handshake")] CcCHandshake = 3001,
    /// <summary>
    /// center  --> center connector 握手反馈
    /// </summary>
    [pbr::OriginalName("C_Cc_Handshake")] CCcHandshake = 3002,
    /// <summary>
    /// center connector --> center 心跳
    /// </summary>
    [pbr::OriginalName("Cc_C_Heartbeat")] CcCHeartbeat = 3003,
    /// <summary>
    /// connector --> center 上行服务器信息数据
    /// </summary>
    [pbr::OriginalName("Cc_C_ServerInfo")] CcCServerInfo = 3005,
    /// <summary>
    /// center --> connector 下行服务器信息数据
    /// </summary>
    [pbr::OriginalName("C_Cc_ServerInfo")] CCcServerInfo = 3006,
    /// <summary>
    /// connector --> center 服务器离线
    /// </summary>
    [pbr::OriginalName("Cc_C_ServerLost")] CcCServerLost = 3007,
    /// <summary>
    /// center --> connector 服务器离线
    /// </summary>
    [pbr::OriginalName("C_Cc_ServerLost")] CCcServerLost = 3008,
    /// <summary>
    /// connector --> center 服务器已准备好
    /// </summary>
    [pbr::OriginalName("Cc_C_ServerOk")] CcCServerOk = 3009,
    /// <summary>
    /// center --> connector 服务器已准备好
    /// </summary>
    [pbr::OriginalName("C_Cc_ServerOk")] CCcServerOk = 3010,
    /// <summary>
    /// center --> connector 关服
    /// </summary>
    [pbr::OriginalName("C_Cc_Stop")] CCcStop = 3011,
    /// <summary>
    /// gate --> gate acceptor 握手
    /// </summary>
    [pbr::OriginalName("Gt_GtA_Handshake")] GtGtAHandshake = 3100,
    /// <summary>
    /// gate acceptor --> gate  握手反馈
    /// </summary>
    [pbr::OriginalName("GtA_Gt_Handshake")] GtAGtHandshake = 3101,
    /// <summary>
    /// gate --> gate acceptor 心跳
    /// </summary>
    [pbr::OriginalName("Gt_GtA_Heartbeat")] GtGtAHeartbeat = 3102,
    /// <summary>
    /// gete --> gate acceptor 客户端连接关闭
    /// </summary>
    [pbr::OriginalName("Gt_GtA_ClientClose")] GtGtAClientClose = 3103,
    /// <summary>
    /// gate acceptor --> gate 主动关闭客户端连接
    /// </summary>
    [pbr::OriginalName("GtA_Gt_ClientDisconnect")] GtAGtClientDisconnect = 3104,
    /// <summary>
    /// gate acceptor --> gate 发往客户端消息
    /// </summary>
    [pbr::OriginalName("GtA_Gt_ClientMessage")] GtAGtClientMessage = 3105,
    /// <summary>
    /// gate acceptor --> gate 广播消息
    /// </summary>
    [pbr::OriginalName("GtA_Gt_Broadcast")] GtAGtBroadcast = 3106,
    /// <summary>
    /// gate acceptor --> gate 设置服务器id
    /// </summary>
    [pbr::OriginalName("GtA_Gt_SetServerId")] GtAGtSetServerId = 3107,
    /// <summary>
    /// db connector --> db 握手
    /// </summary>
    [pbr::OriginalName("Dbc_Db_Handshake")] DbcDbHandshake = 3200,
    /// <summary>
    /// db --> db connector 握手反馈
    /// </summary>
    [pbr::OriginalName("Db_Dbc_Handshake")] DbDbcHandshake = 3201,
    /// <summary>
    /// db connector --> db 心跳
    /// </summary>
    [pbr::OriginalName("Dbc_Db_Heartbeat")] DbcDbHeartbeat = 3202,
    /// <summary>
    /// db connector --> db 请求
    /// </summary>
    [pbr::OriginalName("Dbc_Db_Request")] DbcDbRequest = 3203,
    /// <summary>
    /// db --> db connector 请求结果
    /// </summary>
    [pbr::OriginalName("Db_Dbc_Response")] DbDbcResponse = 3204,
    /// <summary>
    /// hub connector --> hub 握手
    /// </summary>
    [pbr::OriginalName("Hc_H_Handshake")] HcHHandshake = 3300,
    /// <summary>
    /// hub --> hub connector 握手反馈
    /// </summary>
    [pbr::OriginalName("H_Hc_Handshake")] HHcHandshake = 3301,
    /// <summary>
    /// hub connector --> hub 心跳
    /// </summary>
    [pbr::OriginalName("Hc_H_Heartbeat")] HcHHeartbeat = 3302,
    /// <summary>
    /// game --> game 中转测试
    /// </summary>
    [pbr::OriginalName("G_G_HubTest")] GGHubTest = 3400,
    /// <summary>
    ///MESSAGE_ID_END
    /// </summary>
    [pbr::OriginalName("SMSGID_Max")] Max = 5000,
  }

  #endregion

}

#endregion Designer generated code
